import type { Edge, Seed } from "@/lib/domain";

const now = "2026-07-06T16:00:00.000Z";

export const demoSeeds: Seed[] = [
  {
    id: "brain-core",
    versionId: "brain-core-v1",
    kind: "knowledge",
    name: "Pomebrain Core",
    summary: "The governed center that retrieves, routes, validates, and preserves every approved seed.",
    status: "approved",
    podId: "pomebrain",
    confidence: 1,
    tags: ["core", "governance"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-agents",
    versionId: "seed-agents-v1",
    kind: "agent",
    name: "Agents",
    summary: "Purpose-bound AI roles that plan, reason, review, and act with explicit permissions.",
    status: "approved",
    podId: "pomebrain",
    confidence: 0.98,
    tags: ["orchestration", "roles"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-skills",
    versionId: "seed-skills-v1",
    kind: "skill",
    name: "Skills",
    summary: "Portable procedures, scripts, examples, templates, and evaluations used by agents.",
    status: "approved",
    podId: "pomebrain",
    confidence: 0.96,
    tags: ["portable", "tested"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-knowledge",
    versionId: "seed-knowledge-v1",
    kind: "knowledge",
    name: "Knowledge",
    summary: "Evidence-backed patterns, facts, lessons, and constraints retrieved by scope.",
    status: "approved",
    podId: "pomebrain",
    confidence: 0.94,
    tags: ["memory", "evidence"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-tools",
    versionId: "seed-tools-v1",
    kind: "tool",
    name: "Tools",
    summary: "Allowlisted actions and connectors with visible risk and approval requirements.",
    status: "review",
    podId: "pomebrain",
    confidence: 0.88,
    tags: ["connectors", "actions"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-decisions",
    versionId: "seed-decisions-v1",
    kind: "decision",
    name: "Decisions",
    summary: "Chosen directions with their context, rationale, owner, and supersession history.",
    status: "approved",
    podId: "pomebrain",
    confidence: 0.93,
    tags: ["rationale", "history"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-evidence",
    versionId: "seed-evidence-v1",
    kind: "evidence",
    name: "Evidence",
    summary: "Sources, test results, runs, and observations that support or challenge a seed.",
    status: "approved",
    podId: "pomebrain",
    confidence: 0.99,
    tags: ["sources", "tests"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-apps",
    versionId: "seed-apps-v1",
    kind: "project",
    name: "Apps",
    summary: "Products created by the Crown and fed back into the Brain as reusable learning.",
    status: "draft",
    podId: "pomebrain",
    confidence: 0.82,
    tags: ["builds", "artifacts"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-nextjs-boilerplate-architect",
    versionId: "agent-nextjs-boilerplate-architect-v1",
    kind: "agent",
    name: "NextJS Boilerplate Architect",
    summary: "Scaffolds type-safe Next.js App Router projects with Tailwind, TypeScript, absolute imports, and Zod-ready validation layers.",
    status: "draft",
    podId: "engineering",
    confidence: 0.9,
    tags: ["batch-1", "engineering", "nextjs", "scaffold"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-database-schema-provisioner",
    versionId: "agent-database-schema-provisioner-v1",
    kind: "agent",
    name: "Database Schema Provisioner",
    summary: "Generates PostgreSQL schemas, indexes, and Supabase-ready SQL migrations with matching Zod validation expectations.",
    status: "draft",
    podId: "engineering",
    confidence: 0.9,
    tags: ["batch-1", "engineering", "supabase", "postgres"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-supabase-rls-guard",
    versionId: "agent-supabase-rls-guard-v1",
    kind: "agent",
    name: "Supabase RLS Guard",
    summary: "Audits Supabase schemas and crafts strict Row Level Security policies for tenant-safe applications.",
    status: "draft",
    podId: "security",
    confidence: 0.92,
    tags: ["batch-1", "security", "supabase", "rls"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-playwright-e2e-tester",
    versionId: "agent-playwright-e2e-tester-v1",
    kind: "agent",
    name: "Playwright E2E Tester",
    summary: "Drafts and runs Playwright end-to-end tests across user flows, viewport sizes, and preview deployments.",
    status: "draft",
    podId: "quality",
    confidence: 0.88,
    tags: ["batch-1", "quality", "playwright", "testing"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-brief-synthesizer",
    versionId: "agent-brief-synthesizer-v1",
    kind: "agent",
    name: "Brief Synthesizer",
    summary: "Turns loose project goals into structured feature matrices and workflow scopes before engineering begins.",
    status: "draft",
    podId: "product",
    confidence: 0.9,
    tags: ["batch-1", "product", "brief", "scope"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-vercel-deployment-manager",
    versionId: "agent-vercel-deployment-manager-v1",
    kind: "agent",
    name: "Vercel Deployment Manager",
    summary: "Coordinates Vercel preview deployments, deployment logs, environment gates, and production approval handoffs.",
    status: "draft",
    podId: "engineering",
    confidence: 0.88,
    tags: ["batch-1", "engineering", "vercel", "deployment"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-git-merge-orchestrator",
    versionId: "agent-git-merge-orchestrator-v1",
    kind: "agent",
    name: "Git Merge Orchestrator",
    summary: "Packages generated code changes into branches and PRs, maps conflicts, and gates final merges to stable trunk.",
    status: "draft",
    podId: "engineering",
    confidence: 0.88,
    tags: ["batch-1", "engineering", "github", "pr"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-api-token-cost-guard",
    versionId: "agent-api-token-cost-guard-v1",
    kind: "agent",
    name: "API Token Cost Guard",
    summary: "Tracks LLM token consumption, provider usage telemetry, budget run-rates, and cost-per-run warnings.",
    status: "draft",
    podId: "finance",
    confidence: 0.88,
    tags: ["batch-2", "finance", "cost", "tokens"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-pgvector-vectorizing-engine",
    versionId: "agent-pgvector-vectorizing-engine-v1",
    kind: "agent",
    name: "pgvector Vectorizing Engine",
    summary: "Chunks source content, creates embeddings, and prepares pgvector payloads for semantic search in Postgres.",
    status: "draft",
    podId: "data",
    confidence: 0.88,
    tags: ["batch-2", "data", "pgvector", "embeddings"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-analytical-pipeline-builder",
    versionId: "agent-analytical-pipeline-builder-v1",
    kind: "agent",
    name: "Analytical Pipeline Builder",
    summary: "Builds SQL aggregation queries, event metric views, retention cohorts, and product dashboard pipelines.",
    status: "draft",
    podId: "data",
    confidence: 0.88,
    tags: ["batch-2", "data", "analytics", "funnels"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-slack-incident-communicator",
    versionId: "agent-slack-incident-communicator-v1",
    kind: "agent",
    name: "Slack Incident Communicator",
    summary: "Formats operational logs, test failures, status updates, and approval triggers into Slack-ready alerts.",
    status: "draft",
    podId: "operations",
    confidence: 0.86,
    tags: ["batch-2", "operations", "slack", "alerts"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-notion-document-synchronizer",
    versionId: "agent-notion-document-synchronizer-v1",
    kind: "agent",
    name: "Notion Document Synchronizer",
    summary: "Converts approved specs, architecture notes, and decisions into structured Notion wiki pages.",
    status: "draft",
    podId: "operations",
    confidence: 0.86,
    tags: ["batch-2", "operations", "notion", "docs"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-competitor-feature-scraper",
    versionId: "agent-competitor-feature-scraper-v1",
    kind: "agent",
    name: "Competitor Feature Scraper",
    summary: "Explores public pages, API specs, and marketplaces to extract competitive feature patterns.",
    status: "draft",
    podId: "research",
    confidence: 0.84,
    tags: ["batch-2", "research", "competitors", "features"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-tech-stack-evaluation-analyst",
    versionId: "agent-tech-stack-evaluation-analyst-v1",
    kind: "agent",
    name: "Tech-Stack Evaluation Analyst",
    summary: "Checks dependency health, version history, license fit, and public security warnings for external tools.",
    status: "draft",
    podId: "research",
    confidence: 0.86,
    tags: ["batch-2", "research", "dependencies", "security"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-deep-prompt-sanitizer-guard",
    versionId: "agent-deep-prompt-sanitizer-guard-v1",
    kind: "agent",
    name: "Deep Prompt Sanitizer & Guard",
    summary: "Scans untrusted briefs, files, and scraped content for prompt injection, hidden instructions, and malicious payloads before execution.",
    status: "draft",
    podId: "security",
    confidence: 0.9,
    tags: ["batch-3", "security", "prompt-injection", "governance"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-token-throttle-controller",
    versionId: "agent-token-throttle-controller-v1",
    kind: "agent",
    name: "Token Throttle Controller",
    summary: "Tracks live token windows and enforces session quota cutoffs to prevent runaway multi-agent execution loops.",
    status: "draft",
    podId: "finance",
    confidence: 0.88,
    tags: ["batch-3", "finance", "tokens", "throttle"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-dynamic-meta-learner",
    versionId: "agent-dynamic-meta-learner-v1",
    kind: "agent",
    name: "Dynamic Meta-Learner",
    summary: "Analyzes successful builds and logs to propose reusable skills, prompt templates, tool schemas, or agent manifests.",
    status: "draft",
    podId: "research",
    confidence: 0.86,
    tags: ["batch-3", "research", "learning", "foundry"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-logic-reconciliation-engine",
    versionId: "agent-logic-reconciliation-engine-v1",
    kind: "agent",
    name: "Logic Reconciliation Engine",
    summary: "Detects duplicated, overlapping, or conflicting nodes and prepares conflict maps plus supersession proposals for human review.",
    status: "draft",
    podId: "quality",
    confidence: 0.9,
    tags: ["batch-3", "quality", "conflicts", "versions"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-pomebrain-architect-orchestrator",
    versionId: "agent-pomebrain-architect-orchestrator-v1",
    kind: "agent",
    name: "Pomebrain Architect Orchestrator",
    summary: "Master controller that orders graph dependencies, assigns agents, watches evaluations, and resumes from checkpoints.",
    status: "draft",
    podId: "engineering",
    confidence: 0.9,
    tags: ["controller", "orchestration", "app-factory", "continuity"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "skill-app-brief-decomposition",
    versionId: "skill-app-brief-decomposition-v1",
    kind: "skill",
    name: "App Brief Decomposition",
    summary: "Turns conversational app ideas into requirements, data entities, login-to-dashboard workflows, and MVP boundaries.",
    status: "draft",
    podId: "product",
    confidence: 0.88,
    tags: ["skills-batch-1", "product", "brief", "mvp"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "skill-nextjs-app-router-architecture-template",
    versionId: "skill-nextjs-app-router-architecture-template-v1",
    kind: "skill",
    name: "Next.js App Router Architecture Template",
    summary: "Generates deterministic Next.js 14+ folder maps using src/app, src/components, src/modules, and @/* imports.",
    status: "draft",
    podId: "engineering",
    confidence: 0.88,
    tags: ["skills-batch-1", "engineering", "nextjs", "architecture"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "skill-type-safe-zod-validator-scaffolding",
    versionId: "skill-type-safe-zod-validator-scaffolding-v1",
    kind: "skill",
    name: "Type-Safe Zod Validator Scaffolding",
    summary: "Compiles runtime-safe Zod validators from database table schemas or structured entity definitions.",
    status: "draft",
    podId: "engineering",
    confidence: 0.88,
    tags: ["skills-batch-1", "engineering", "zod", "validation"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "skill-multi-tenant-rls-generation",
    versionId: "skill-multi-tenant-rls-generation-v1",
    kind: "skill",
    name: "Multi-Tenant RLS Generation",
    summary: "Produces Supabase/Postgres RLS policy SQL for tenant-safe CRUD access with anonymous-deny fallback.",
    status: "draft",
    podId: "security",
    confidence: 0.9,
    tags: ["skills-batch-1", "security", "supabase", "rls"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "skill-playwright-e2e-form-scripting",
    versionId: "skill-playwright-e2e-form-scripting-v1",
    kind: "skill",
    name: "Playwright E2E Form Scripting",
    summary: "Builds Playwright scripts for form submissions, error banners, redirects, and success-state checks.",
    status: "draft",
    podId: "quality",
    confidence: 0.86,
    tags: ["skills-batch-1", "quality", "playwright", "forms"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "skill-semantic-contradiction-reconciliation",
    versionId: "skill-semantic-contradiction-reconciliation-v1",
    kind: "skill",
    name: "Semantic Contradiction Reconciliation",
    summary: "Compares incoming seed proposals against existing entries to detect duplicates, contradictions, and supersession candidates.",
    status: "draft",
    podId: "quality",
    confidence: 0.9,
    tags: ["skills-batch-1", "quality", "conflicts", "reconciliation"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "skill-recursive-task-resolution-loop",
    versionId: "skill-recursive-task-resolution-loop-v1",
    kind: "skill",
    name: "Recursive Task Resolution Loop",
    summary: "Scans project graph tasks, orders dependencies, dispatches agents, evaluates outputs, logs evidence, and resumes from checkpoints.",
    status: "draft",
    podId: "engineering",
    confidence: 0.9,
    tags: ["orchestration", "execution-loop", "continuity"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "connector-supabase-mcp",
    versionId: "connector-supabase-mcp-v1",
    kind: "connector",
    name: "Supabase MCP Connector",
    summary: "Server-side MCP adapter for database reads, schema inspection, and gated Supabase migration execution.",
    status: "review",
    podId: "connectors",
    confidence: 0.84,
    tags: ["mcp", "supabase", "server-only"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "connector-github-mcp",
    versionId: "connector-github-mcp-v1",
    kind: "connector",
    name: "GitHub MCP Connector",
    summary: "Server-side MCP adapter for branch management, pull request creation, and gated merge operations.",
    status: "review",
    podId: "connectors",
    confidence: 0.84,
    tags: ["mcp", "github", "pull-requests"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "connector-vercel-mcp",
    versionId: "connector-vercel-mcp-v1",
    kind: "connector",
    name: "Vercel MCP Connector",
    summary: "Server-side MCP adapter for preview deployments and owner-approved production promotion.",
    status: "review",
    podId: "connectors",
    confidence: 0.84,
    tags: ["mcp", "vercel", "deployments"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "connector-anthropic-mcp",
    versionId: "connector-anthropic-mcp-v1",
    kind: "connector",
    name: "Anthropic MCP Connector",
    summary: "Server-side MCP adapter for Claude model routing through governed LLM cross-route capabilities.",
    status: "review",
    podId: "connectors",
    confidence: 0.82,
    tags: ["mcp", "anthropic", "claude", "server-only"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "connector-openai-mcp",
    versionId: "connector-openai-mcp-v1",
    kind: "connector",
    name: "OpenAI MCP Connector",
    summary: "Server-side MCP adapter for OpenAI model routing through governed LLM cross-route capabilities.",
    status: "review",
    podId: "connectors",
    confidence: 0.82,
    tags: ["mcp", "openai", "llm", "server-only"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "connector-google-workspace-mcp",
    versionId: "connector-google-workspace-mcp-v1",
    kind: "connector",
    name: "Google Workspace MCP Connector",
    summary: "Server-side MCP adapter for Drive reads/writes and team-confirmed Gmail sending.",
    status: "review",
    podId: "connectors",
    confidence: 0.82,
    tags: ["mcp", "google-workspace", "drive", "gmail"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "connector-fathom-mcp",
    versionId: "connector-fathom-mcp-v1",
    kind: "connector",
    name: "Fathom MCP Connector",
    summary: "Server-side MCP adapter for read-only product traffic and conversion analytics.",
    status: "review",
    podId: "connectors",
    confidence: 0.82,
    tags: ["mcp", "fathom", "analytics"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "policy-capability-matrix",
    versionId: "policy-capability-matrix-v1",
    kind: "policy",
    name: "Granular Capability Matrix",
    summary: "Maps agent capability IDs to MCP connector actions, safety classes, and default approval rules.",
    status: "review",
    podId: "governance",
    confidence: 0.9,
    tags: ["mcp", "policy", "approval"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tool-execute-capability-rpc",
    versionId: "tool-execute-capability-rpc-v1",
    kind: "tool",
    name: "Execute Capability RPC",
    summary: "Server-side `/api/v1/rpc/execute_capability` endpoint that validates, audits, gates, and routes capability requests.",
    status: "review",
    podId: "governance",
    confidence: 0.9,
    tags: ["mcp", "rpc", "audit"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "artifact-phase-4-app-factory-schema",
    versionId: "artifact-phase-4-app-factory-schema-v1",
    kind: "artifact",
    name: "Phase 4 App Factory Schema",
    summary: "Supabase migration asset for projects, project_runs, build_tasks, and approval_queue tables that power the Orchestrator loop.",
    status: "review",
    podId: "app-factory",
    confidence: 0.9,
    tags: ["phase-4", "supabase", "schema", "app-factory"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "artifact-approval-queue",
    versionId: "artifact-approval-queue-v1",
    kind: "artifact",
    name: "Human Approval Queue",
    summary: "Database gatekeeper table for high-risk capabilities such as migrations, merges, Gmail sends, and production deploys.",
    status: "review",
    podId: "governance",
    confidence: 0.9,
    tags: ["phase-4", "approval", "governance"],
    createdAt: now,
    updatedAt: now,
  },
];

const coreEdges: Edge[] = [
  ["agents", "seed-agents", "uses"],
  ["skills", "seed-skills", "uses"],
  ["knowledge", "seed-knowledge", "learned_from"],
  ["tools", "seed-tools", "requires"],
  ["decisions", "seed-decisions", "supported_by"],
  ["evidence", "seed-evidence", "validated_by"],
  ["apps", "seed-apps", "produces"],
].map(([id, targetId, kind]) => ({
  id: `edge-${id}`,
  sourceId: "brain-core",
  targetId,
  kind: kind as Edge["kind"],
  strength: 0.9,
  createdAt: now,
}));

const batchOneAgentEdges: Edge[] = [
  "agent-nextjs-boilerplate-architect",
  "agent-database-schema-provisioner",
  "agent-supabase-rls-guard",
  "agent-playwright-e2e-tester",
  "agent-brief-synthesizer",
  "agent-vercel-deployment-manager",
  "agent-git-merge-orchestrator",
].map((targetId) => ({
  id: `edge-seed-agents-${targetId}`,
  sourceId: "seed-agents",
  targetId,
  kind: "belongs_to" as Edge["kind"],
  strength: 0.86,
  createdAt: now,
}));

const batchTwoAgentEdges: Edge[] = [
  "agent-api-token-cost-guard",
  "agent-pgvector-vectorizing-engine",
  "agent-analytical-pipeline-builder",
  "agent-slack-incident-communicator",
  "agent-notion-document-synchronizer",
  "agent-competitor-feature-scraper",
  "agent-tech-stack-evaluation-analyst",
].map((targetId) => ({
  id: `edge-seed-agents-${targetId}`,
  sourceId: "seed-agents",
  targetId,
  kind: "belongs_to" as Edge["kind"],
  strength: 0.84,
  createdAt: now,
}));

const batchThreeAgentEdges: Edge[] = [
  "agent-deep-prompt-sanitizer-guard",
  "agent-token-throttle-controller",
  "agent-dynamic-meta-learner",
  "agent-logic-reconciliation-engine",
  "agent-pomebrain-architect-orchestrator",
].map((targetId) => ({
  id: `edge-seed-agents-${targetId}`,
  sourceId: "seed-agents",
  targetId,
  kind: "belongs_to" as Edge["kind"],
  strength: 0.86,
  createdAt: now,
}));

const skillBatchOneEdges: Edge[] = [
  "skill-app-brief-decomposition",
  "skill-nextjs-app-router-architecture-template",
  "skill-type-safe-zod-validator-scaffolding",
  "skill-multi-tenant-rls-generation",
  "skill-playwright-e2e-form-scripting",
  "skill-semantic-contradiction-reconciliation",
  "skill-recursive-task-resolution-loop",
].map((targetId) => ({
  id: `edge-seed-skills-${targetId}`,
  sourceId: "seed-skills",
  targetId,
  kind: "belongs_to" as Edge["kind"],
  strength: 0.86,
  createdAt: now,
}));

const agentSkillEdges: Edge[] = [
  ["agent-brief-synthesizer", "skill-app-brief-decomposition"],
  ["agent-nextjs-boilerplate-architect", "skill-nextjs-app-router-architecture-template"],
  ["agent-nextjs-boilerplate-architect", "skill-type-safe-zod-validator-scaffolding"],
  ["agent-database-schema-provisioner", "skill-type-safe-zod-validator-scaffolding"],
  ["agent-supabase-rls-guard", "skill-multi-tenant-rls-generation"],
  ["agent-playwright-e2e-tester", "skill-playwright-e2e-form-scripting"],
  ["agent-logic-reconciliation-engine", "skill-semantic-contradiction-reconciliation"],
  ["agent-pomebrain-architect-orchestrator", "skill-recursive-task-resolution-loop"],
].map(([sourceId, targetId]) => ({
  id: `edge-${sourceId}-${targetId}`,
  sourceId,
  targetId,
  kind: "uses" as Edge["kind"],
  strength: 0.9,
  createdAt: now,
}));

const connectorLayerEdges: Edge[] = [
  ["seed-tools", "connector-supabase-mcp", "requires"],
  ["seed-tools", "connector-github-mcp", "requires"],
  ["seed-tools", "connector-vercel-mcp", "requires"],
  ["seed-tools", "connector-anthropic-mcp", "requires"],
  ["seed-tools", "connector-openai-mcp", "requires"],
  ["seed-tools", "connector-google-workspace-mcp", "requires"],
  ["seed-tools", "connector-fathom-mcp", "requires"],
  ["seed-tools", "tool-execute-capability-rpc", "uses"],
  ["tool-execute-capability-rpc", "policy-capability-matrix", "applies_to"],
  ["connector-supabase-mcp", "policy-capability-matrix", "applies_to"],
  ["connector-github-mcp", "policy-capability-matrix", "applies_to"],
  ["connector-vercel-mcp", "policy-capability-matrix", "applies_to"],
  ["connector-anthropic-mcp", "policy-capability-matrix", "applies_to"],
  ["connector-openai-mcp", "policy-capability-matrix", "applies_to"],
  ["connector-google-workspace-mcp", "policy-capability-matrix", "applies_to"],
  ["connector-fathom-mcp", "policy-capability-matrix", "applies_to"],
].map(([sourceId, targetId, kind]) => ({
  id: `edge-${sourceId}-${targetId}`,
  sourceId,
  targetId,
  kind: kind as Edge["kind"],
  strength: 0.9,
  createdAt: now,
}));

const appFactorySchemaEdges: Edge[] = [
  ["seed-apps", "artifact-phase-4-app-factory-schema", "requires"],
  ["agent-pomebrain-architect-orchestrator", "artifact-phase-4-app-factory-schema", "uses"],
  ["skill-recursive-task-resolution-loop", "artifact-phase-4-app-factory-schema", "requires"],
  ["artifact-phase-4-app-factory-schema", "artifact-approval-queue", "produces"],
  ["artifact-approval-queue", "policy-capability-matrix", "applies_to"],
].map(([sourceId, targetId, kind]) => ({
  id: `edge-${sourceId}-${targetId}`,
  sourceId,
  targetId,
  kind: kind as Edge["kind"],
  strength: 0.9,
  createdAt: now,
}));

export const demoEdges: Edge[] = [
  ...coreEdges,
  ...batchOneAgentEdges,
  ...batchTwoAgentEdges,
  ...batchThreeAgentEdges,
  ...skillBatchOneEdges,
  ...agentSkillEdges,
  ...connectorLayerEdges,
  ...appFactorySchemaEdges,
];
